name: path_pilot
description: "Create, upload, and analyze precise path instructions for line-following robots."
repository: https://github.com/Cupcake-Systems/path_pilot
issue_tracker: https://github.com/Cupcake-Systems/path_pilot/issues

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.4
  file_picker: ^8.0.6
  path: ^1.9.0
  url_launcher: ^6.3.0
  fl_chart: ^0.69.0
  shared_preferences: ^2.2.3
  package_info_plus: ^8.0.0
  flutter_resizable_container: ^3.0.0
  permission_handler: ^11.3.1
  device_info_plus: ^11.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf

  assets:
    - assets/robi_illustration.webp
    - assets/robi_illustration_bottom_labeled.webp
