name: robi_line_drawer
description: "An app to draw lines for the robi to follow."
repository: https://github.com/Finnomator/robi_line_drawer
issue_tracker: https://github.com/Finnomator/robi_line_drawer/issues

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.4
  file_picker: ^8.0.6
  path: ^1.9.0
  url_launcher: ^6.3.1
  fl_chart: ^0.69.0
  shared_preferences: ^2.2.3
  package_info_plus: ^8.0.0
  curved_gradient: ^0.3.0
  universal_ble: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
